// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	"home": {
		"title": "G.R.I.M.O.I.R.E",
		"subtitle": "¡Desata tu imaginación en aventuras de D&D!",
		"slide0": "Director de juego con IA, panel de campaña y VTT inmersivo.",
		"slide1": "Sube tus recursos de campaña y deja que la magia comience.",
		"slide2": "Colabora, explora y crea historias inolvidables."
	},
	"error": {
		"title": "Algo salió mal",
		"description": "Ocurrió un error inesperado. Por favor, inténtalo de nuevo.",
		"retry": "Reintentar"
	},
	"theme": {
		"light": "Claro",
		"dark": "Oscuro",
		"system": "Sistema",
		"toggle": "Cambiar tema"
	},
	"locale": {
		"change": "Cambiar idioma",
		"en": "Inglés",
		"en_alt": "Inglés de EE.UU.",
		"es": "Español",
		"es_alt": "Español de España",
		"pt": "Portugués",
		"pt_alt": "Portugués Brasileño"
	}
};
export default messages;